export { default as Home } from "./Home/Home"
export { default as Donation } from "./Donation/Donation"
export { default as SingleEvent } from "./SingleEvent/SingleEvent"
export { default as Events } from "./Events/Events"
export { default as Success } from "./Donation/Success/Success"
export { default as PageNotFound } from "./PageNotFound/PageNotFound"
export { default as JoinUs } from "./JoinUs/JoinUs"
// export { default as Contact } from "./Contact/Contact"
export { default as About } from "./About/About"
export { default as LoadingScreen } from "./LoadingScreen/LoadingScreen"